name: Deploy Typsite site to Pages

on:
  push:
    branches: [ main, dev ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - uses: typst-community/setup-typst@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          rustflags: --cfg tokio_unstable
          override: true
      - name: Build Typsite
        run: |
          cd src
          cargo build --release
      - name: Copy Typsite
        run: |
          cp ./target/release/typsite ./typsite
      - name: Make binary executable
        run: chmod +x ./typsite
      - name: Typsite init 
        run: |
          ./typsite init
      # Here we have to try multiple times
      # since there are network error caused by typst packages randomly
      - name: Typsite compile
        continue-on-error: true
        id: compile_1
        run: |
          ./typsite clean
          ./typsite c
      - name: Typsite compile (retry 1)
        continue-on-error: true
        id: compile_2
        if: steps.compile_1.outcome == 'failure'
        run: |
          ./typsite clean
          ./typsite c
      - name: Typsite compile (retry 2)
        continue-on-error: true
        id: compile_3
        if: steps.compile2.outcome == 'failure'
        run: |
          ./typsite clean
          ./typsite c
      - name: Typsite compile (retry 3)
        id: compile_4
        if: steps.compile3.outcome == 'failure'
        run: |
          ./typsite clean
          ./typsite c
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
